nnn: dvtm: fzy-{cd,open}: open in fullscreen mode
File pathes might be long and do not fit into nnn
default space, so lets open it in fullscreen mode
and then back to normal view.

Signed-off-by: Vadym Kochan <vadim4j@gmail.com>

diff --git a/configs/apps/nnn/plugins/dvtm/fzy-cd b/configs/apps/nnn/plugins/dvtm/fzy-cd
--- a/configs/apps/nnn/plugins/dvtm/fzy-cd
+++ b/configs/apps/nnn/plugins/dvtm/fzy-cd
@@ -5,12 +5,20 @@
 # Shell: POSIX compliant
 # Author: Vadym Kochan
 
+if [ -z "$DVTM_CMD_FIFO" ]; then
+	echo 'ERROR: $DVTM_CMD_FIFO is not set' | ${PAGER:-less}
+	exit 2
+fi
 if [ -z "$NNN_PIPE" ]; then
 	echo 'ERROR: $NNN_PIPE is not set' | ${PAGER:-less}
 	exit 2
 fi
 
+printf "setlayout \"[ ]\"\n" > ${DVTM_CMD_FIFO}
+
 sel=$(find -type d | fzy -s -l 20)
+
+printf "setlayout\n" > ${DVTM_CMD_FIFO}
 
 if [ -n "${sel}" ]; then
 	path=$(readlink -f $sel)
